#!/bin/sh
# This is a placeholder. Real Gradle wrapper should be generated by:
#   gradle wrapper --gradle-version 8.2
# Or download from: https://services.gradle.org/distributions/gradle-8.2-bin.zip

echo "Gradle wrapper not installed."
echo "Download from: https://services.gradle.org/distributions/gradle-8.2-bin.zip"
echo "Or run: gradle wrapper --gradle-version 8.2"
exit 1
